// All user-facing UI copy (Russian). Centralised for consistency.

export const t = {
  app: {
    brandTop: "DOTA 2 · ИНХАУС",
    wordmark: "5×5",
    tagline: "Балансировщик лобби",
    addPlayer: "Добавить игрока",
    sendToDiscord: "Отправить в Discord",
    mmr: "ММР",
  },

  data: {
    export: "Экспорт",
    import: "Импорт",
    exporting: "Экспорт…",
    importing: "Импорт…",
    exportTitle: "Сохранить все данные в файл",
    importTitle: "Импорт данных",
    exportedToast: (path: string) => `Файл сохранён: ${path}`,
    exportFailed: "Не удалось экспортировать данные.",
    importPrompt: "Импортировать этот файл?",
    importWarning: "Все текущие игроки, расстановка и настройки будут заменены.",
    importPlayers: (n: number) => `Игроков в файле: ${n}`,
    importBadFile: "Неверный файл данных. Выберите файл, созданный кнопкой «Экспорт».",
    importFailed: "Не удалось импортировать данные.",
    confirm: "Импортировать",
    cancel: "Отмена",
  },

  roster: {
    title: "Активные игроки",
    onBoard: (n: number) => `${n} в командах`,
    filter: "Поиск игрока…",
    loading: "Загрузка…",
    emptyFiltered: "Ничего не найдено.",
    emptyAllPlaced: "Все активные игроки в командах. Перетащите карточку сюда, чтобы вернуть в запас.",
    emptyNone: "Пока нет игроков. Нажмите «Добавить игрока», чтобы собрать состав.",
    emptyNoActive: "Нет активных игроков. Откройте «Все игроки» и отметите, кто онлайн.",
    allPlayers: "Все игроки",
  },

  allPlayers: {
    title: "Все игроки",
    subtitle: "Отметьте, кто онлайн, измените данные или удалите игрока из системы.",
    filter: "Поиск игрока…",
    count: (n: number) => `${n} всего`,
    active: (n: number) => `${n} онлайн`,
    empty: "Ничего не найдено.",
    emptyNone: "Пока нет игроков.",
  },

  card: {
    mmr: "ММР",
    openSteam: "Открыть профиль Steam",
    editMmr: "Изменить ММР",
    refresh: "Обновить из Dota",
    edit: "Изменить",
    delete: "Удалить",
    confirmDelete: "Удалить игрока?",
    cancel: "Отмена",
    noDiscord: "Ссылка на Discord не указана",
    removeFromActive: "Убрать из активных (не удаляет из системы)",
    markOnline: "Отметить онлайн",
    markOffline: "Отметить офлайн",
  },

  modal: {
    titleAdd: "Добавить игрока",
    titleEdit: "Изменить игрока",
    titleConfirm: "Проверьте данные",
    searchLabel: "Имя в Steam, SteamID или ссылка на профиль",
    searchPlaceholder: "напр. Dendi · 76561198… · steamcommunity.com/profiles/…",
    search: "Найти",
    searchHint: "Подтянет аватар и ранг из Dota. Или заполните поля вручную.",
    noResults: "Игроки с таким именем не найдены.",
    account: (id: number) => `аккаунт ${id}`,
    manualPrompt: "Приватный профиль или нет Steam?",
    manual: "Ввести вручную",
    privateBanner: "Профиль Dota приватный или не проиндексирован — заполните данные вручную.",
    steamName: "Имя в Steam",
    steamNamePlaceholder: "Отображаемое имя",
    rank: "Ранг",
    mmrEditable: "ММР (можно изменить)",
    mmrPlaceholder: "напр. 5500",
    discordName: "Ник в Discord",
    discordNamePlaceholder: "напр. player#0001",
    discordId: "Discord ID (для пинга)",
    discordIdPlaceholder: "напр. 123456789012345678",
    discordIdHint: "Включите режим разработчика в Discord → ПКМ по игроку → «Копировать ID».",
    notes: "Заметки (необязательно)",
    notesPlaceholder: "Роли, время игры, …",
    back: "← Назад к поиску",
    save: "Сохранить",
    saving: "Сохранение…",
    errNameRequired: "Укажите имя в Steam.",
    errMmr: "Введите корректное число ММР.",
    roles: "Позиции",
    rolesHint: "Можно выбрать несколько.",
    rolesAll: "Все",
    avatar: "Аватар",
    avatarUpload: "Загрузить фото",
    avatarRemove: "Убрать фото",
    avatarHint: "PNG или JPG с вашего компьютера.",
    avatarTooLarge: "Файл слишком большой (макс. 3 МБ).",
  },

  roles: {
    1: "Позиция 1 (Carry)",
    2: "Позиция 2 (Mid)",
    3: "Позиция 3 (Offlane)",
    4: "Позиция 4 (Soft Support)",
    5: "Позиция 5 (Hard Support)",
  } as Record<number, string>,

  board: {
    title: "Расстановка",
    subtitle: "Перетаскивайте игроков в слоты, чтобы выровнять ММР команд.",
    clear: "Очистить",
    radiant: "Свет",
    dire: "Тьма",
    teamA: "Команда A",
    teamB: "Команда B",
    teamMmr: "ММР команды",
    avg: "сред.",
    slot: (n: number) => `Слот ${n}`,
    removeFromTeam: "Убрать из команды",
  },

  balance: {
    title: "Разница ММР",
    balanced: "Идеальный баланс",
    slight: "Небольшой перевес",
    unbalanced: "Сильный дисбаланс",
    favouredRadiant: "перевес у Света",
    favouredDire: "перевес у Тьмы",
    even: "силы равны",
  },

  lobby: {
    title: "Лобби",
    region: "Регион",
    regionNone: "Выберите регион",
    regionSearch: "Поиск региона…",
    regionEmpty: "Ничего не найдено",
    regionClear: "— Сбросить —",
    roomName: "Название комнаты",
    roomNamePlaceholder: "напр. Inhouse #1",
    password: "Пароль",
    passwordPlaceholder: "напр. dota",
    show: "Показать пароль",
    hide: "Скрыть пароль",
    copy: "Скопировать",
    copied: "Скопировано",
  },

  coin: {
    button: "Жребий",
    title: "Жребий",
    hint: "Кто выбирает игрока первым",
    flipping: "Бросаем…",
    resultPrefix: "Первым выбирает",
    teamA: "Команда A · Свет",
    teamB: "Команда B · Тьма",
    again: "Ещё раз",
  },

  discord: {
    settingsTitle: "Настройки Discord",
    settings: "Настройки",
    webhook: "Discord webhook URL",
    webhookPlaceholder: "https://discord.com/api/webhooks/…",
    webhookHint:
      "В нужном канале: Настройки → Интеграции → Вебхуки → Создать вебхук → Копировать URL.",
    save: "Сохранить",
    sending: "Отправка…",
    sent: "Отправлено в Discord",
    failed: "Не удалось отправить",
    noWebhook: "Сначала укажите webhook (шестерёнка справа).",
    confirmTitle: "Отправить в Discord",
    confirmPingIntro: (n: number) => `Будут упомянуты (@) ${n} игрок(ов) из команд:`,
    confirmNoPing: "Ни у кого из расставленных игроков нет Discord ID — никто не будет упомянут.",
    confirmDupWarning: "Один Discord ID указан у нескольких игроков — это один и тот же человек.",
    confirmSend: "Отправить",
    cancel: "Отмена",
  },
} as const;

/** Dota 2 server regions. The selected label string is stored in the DB. */
export const REGIONS: string[] = [
  "Australia (Sydney)",
  "Chile (Santiago)",
  "Dubai (UAE)",
  "Europe East 1 (Vienna, Austria)",
  "Europe East 2 (Vienna, Austria)",
  "Europe East (Vienna, Austria)",
  "Europe West 1 (Luxembourg)",
  "Europe West 2 (Luxembourg)",
  "Europe West (Amsterdam, Netherlands)",
  "Europe West (Madrid, Spain)",
  "Europe (Warsaw, Poland)",
  "Europe (Stockholm, Sweden)",
  "India (Kolkata)",
  "Peru (Lima)",
  "Russia 1 (Stockholm, Sweden)",
  "Russia 2 (Stockholm, Sweden)",
  "SE Asia 1 (Singapore)",
  "SE Asia 2 (Singapore)",
  "South East Asia (Singapore)",
  "South Africa 1 (Cape Town)",
  "South Africa 2 (Cape Town)",
  "South Africa 3 (Cape Town)",
  "South Africa 4 (Johannesburg)",
  "Africa (Johannesburg, South Africa)",
  "South America 1 (Sao Paulo)",
  "South America 2 (Sao Paulo)",
  "South America 3 (Sao Paulo)",
  "US East (Sterling, VA)",
  "US West (Seattle, WA)",
  "US West (Bellevue, Washington)",
  "US West (Los Angeles, California)",
  "US West (Salt Lake City, Utah)",
  "West Asia (Bengaluru, India)",
  "East Asia (Tokyo, Japan)",
  "East Asia (Chiyoda, Japan)",
  "Oceania (Sydney, Australia)",
];
